# Generated by Django 3.2.5 on 2021-08-16 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_games'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Games',
        ),
    ]
