# Generated by Django 3.2.5 on 2021-08-16 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_delete_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_provider',
        ),
    ]
