# Generated by Django 3.2.5 on 2021-08-16 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gametype', models.CharField(choices=[('FPS GAME', 'FPS GAME'), ('TPS GAME', 'TPS GAME'), ('SPS GAME', 'SPS GAME')], max_length=255)),
                ('gamename', models.CharField(max_length=255)),
                ('availableat', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
